# Generated by Django 3.2.12 on 2022-05-07 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name='账户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('name', models.CharField(max_length=40, verbose_name='公司名称')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('mail', models.CharField(max_length=20, verbose_name='邮箱')),
                ('photo', models.ImageField(upload_to='static/images/company', verbose_name='照片')),
                ('address', models.CharField(max_length=300, verbose_name='公司地址')),
                ('info', models.CharField(max_length=1000, verbose_name='公司介绍')),
                ('status', models.BooleanField(default=False, verbose_name='审核通过')),
            ],
            options={
                'verbose_name': '企业管理',
                'verbose_name_plural': '企业管理',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_status', models.SmallIntegerField(choices=[(1, '待处理'), (2, '已接受'), (3, '已拒绝')], default=1, verbose_name='应聘者状态')),
                ('status', models.SmallIntegerField(choices=[(1, '未开始'), (2, '未通过'), (3, '已通过')], default=1, verbose_name='面试结果')),
                ('time', models.DateTimeField(blank=True, default=None, max_length=200, null=True, verbose_name='面试时间')),
                ('meetingid', models.CharField(default='', max_length=100, verbose_name='会议号')),
                ('create', models.DateTimeField(auto_now_add=True, max_length=200, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '面试邀请管理',
                'verbose_name_plural': '面试邀请管理',
                'db_table': 'interview',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='职位名称')),
                ('workcity', models.CharField(max_length=50, verbose_name='工作城市')),
                ('salary_start', models.IntegerField(verbose_name='最低薪资')),
                ('salary_end', models.IntegerField(verbose_name='最高薪资')),
                ('salary', models.CharField(max_length=200, verbose_name='薪资要求')),
                ('education', models.CharField(max_length=200, verbose_name='学历要求')),
                ('experience', models.CharField(max_length=200, verbose_name='经验要求')),
                ('content', models.CharField(max_length=600, verbose_name='职位需求')),
                ('create', models.DateTimeField(auto_now_add=True, max_length=200, verbose_name='发布日期')),
                ('heat', models.IntegerField(default=0, verbose_name='热度')),
            ],
            options={
                'verbose_name': '职位管理',
                'verbose_name_plural': '职位管理',
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='职位类型')),
            ],
            options={
                'verbose_name': '职位类型管理',
                'verbose_name_plural': '职位类型管理',
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单id')),
                ('create', models.DateTimeField(auto_now_add=True, max_length=200, verbose_name='投递时间')),
                ('status', models.SmallIntegerField(choices=[(1, '投递成功'), (2, '被查看'), (3, '邀面试'), (4, '不合适')], default=1, verbose_name='状态')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='职位')),
            ],
            options={
                'verbose_name': '简历投递管理',
                'verbose_name_plural': '简历投递管理',
                'db_table': 'send',
            },
        ),
    ]
