# Generated by Django 3.2.12 on 2022-05-07 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.resume', verbose_name='简历'),
        ),
        migrations.AddField(
            model_name='send',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='企业'),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.type', verbose_name='职位类型'),
        ),
        migrations.AddField(
            model_name='interview',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='企业'),
        ),
        migrations.AddField(
            model_name='interview',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job', verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='interview',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.resume', verbose_name='简历'),
        ),
        migrations.AddField(
            model_name='interview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='应聘者'),
        ),
    ]
