# Generated by Django 3.2.12 on 2022-05-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svalue', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='字段')),
                ('snumble', models.IntegerField(default=0, verbose_name='出现次数')),
            ],
            options={
                'verbose_name': '词云管理',
                'verbose_name_plural': '词云管理',
                'db_table': 'searchdata',
            },
        ),
    ]
